version: '3.9'
services:
  tetish-inn-frontend:
    image: abzed/tetish-inn-frontend
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - tetish-inn-backend

  tetish-inn-backend:
    image: abzed/tetish-inn-backend
    ports:
      - "3000:3000"
    restart: always