
default: &default
  adapter: postgresql
  encoding: unicode
  username: ibraa
  password: <%= ENV["DATABASE_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tetish_inn


production:
  <<: *default
  host: <%= ENV['AWS_RDS_HOST'] %>
  post: 5432
  database: tetish_inn
  
