apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tetish-inn-backend
    version: v1
  name: tetish-inn-backend
  namespace: default

spec:
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      app: tetish-inn-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tetish-inn-backend
        version: v1
    spec:
      containers:
      - image: abzed/tetish-inn-backend:v6
        imagePullPolicy: IfNotPresent
        name: tetish-inn-backend
        env:
          - name: RAILS_ENV
            valueFrom:
              configMapKeyRef:
                key: RAILS_ENV
                name: tetish-inn-config

          - name: DATABASE_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: DATABASE_PASSWORD
                name: tetish-inn-config

          - name: CLOUD_NAME
            valueFrom:
              configMapKeyRef:
                key: CLOUD_NAME
                name: tetish-inn-config

          - name: CLOUD_API_KEY
            valueFrom:
              configMapKeyRef:
                key: CLOUD_API_KEY
                name: tetish-inn-config

          - name: CLOUD_API_SECRET
            valueFrom:
              configMapKeyRef:
                key: CLOUD_API_SECRET
                name: tetish-inn-config

          - name: AWS_RDS_HOST
            valueFrom:
              configMapKeyRef:
                key: AWS_RDS_HOST
                name: tetish-inn-config

        resources:
          requests:
            cpu: 100m
            memory: 112Mi
          limits:
            cpu: 200m
            memory: 224Mi

      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tetish-inn-backend
  name: tetish-inn-backend
  namespace: default
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    # - name: http
    #   protocol: TCP
    #   port: 80
    #   targetPort: 9376
    # - name: https
    #   protocol: TCP
    #   port: 443
    #   targetPort: 9377
  selector:
    app: tetish-inn-backend
  sessionAffinity: None
  type: NodePort

